hubspot_debug_on: 1
tracking_code_on: 0
hubspot_portal_id: '45907613'
hubspot_client_id: bab408b1-2659-4f0a-808f-78b4013714e3
hubspot_client_secret: 20072dfb-0a7a-440f-8162-f1a345f63dfd
hubspot_scope: 'forms oauth'
hubspot_debug_email: fly2kishor@gmail.com
